config/routes.rb
  get "tutores/buscar_persona" 
  get "tutores/tutor_detalle"
  get "tutores/agregar_tutor_detalle"
  post "tutores/guardar_tutor_detalle"
  get "tutores/eliminar_tutor_detalle"
  
  #CARGOS
  post 'cargos/lista'
  get 'cargos/lista'
  get 'cargos/agregar'
  post 'cargos/guardar'
  get 'cargos/eliminar'
  get 'cargos/editar'
  post 'cargos/actualizar'
  get 'cargos/index'

  #REMUNERACIONES EXTRAS
  post 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/agregar'
  post 'pagos_remuneraciones_extras/guardar'
  get 'pagos_remuneraciones_extras/eliminar'
  get 'pagos_remuneraciones_extras/editar'
  post 'pagos_remuneraciones_extras/actualizar'
  get 'pagos_remuneraciones_extras/index'

#DESCUENTOS
  post 'pagos_descuentos/lista'
  get 'pagos_descuentos/lista'
  get 'pagos_descuentos/agregar'
  post 'pagos_descuentos/guardar'
  get 'pagos_descuentos/eliminar'
  get 'pagos_descuentos/editar'
  post 'pagos_descuentos/actualizar'
  get 'pagos_descuentos/index'

#ADELANTOS
  post 'pagos_adelantos/lista'
  get 'pagos_adelantos/lista'
  get 'pagos_adelantos/agregar'
  post 'pagos_adelantos/guardar'
  get 'pagos_adelantos/eliminar'
  get 'pagos_adelantos/editar'
  post 'pagos_adelantos/actualizar'
  get 'pagos_adelantos/index'

#PAGOS DE SALARIOS
  get 'pagos_salarios/index'
  post 'pagos_salarios/lista'
  get 'pagos_salarios/lista'
  get 'pagos_salarios/agregar'
  post 'pagos_salarios/guardar'
  get 'pagos_salarios/eliminar'
  get 'pagos_salarios/salario_detalle'

  #ADELANTOS
  post 'registros_gastos/lista'
  get 'registros_gastos/lista'
  get 'registros_gastos/agregar'
  post 'registros_gastos/guardar'
  get 'registros_gastos/eliminar'
  get 'registros_gastos/editar'
  post 'registros_gastos/actualizar'
  get 'registros_gastos/index'
#---------------------------------------FONOWARE------------------------------------------------------------------------    
  #CRONTAB
  get "crontab_ultron/index"

  #JURISDICCIONES
  get "jurisdicciones/index"
  get "jurisdicciones/buscar_juridisccion_oferta" 

  #INFORMES
  get "informes/index"
  get "informes/index_gastos"
  get "informes/index_balance"
  get "informes/indexa"
  get "informes/generar_pdf"

  #DETALLES DEBITOS
  post "detalles_debitos/lista"
  get "detalles_debitos/lista"
  get "detalles_debitos/agregar"
  post "detalles_debitos/guardar"
  get "detalles_debitos/eliminar"
  get "detalles_debitos/editar"
  post "detalles_debitos/actualizar"
  get "detalles_debitos/index"
 
  #DETALLES CREDITOS
  post "detalles_creditos/lista"
  get "detalles_creditos/lista"
  get "detalles_creditos/agregar"
  post "detalles_creditos/guardar"
  get "detalles_creditos/eliminar"
  get "detalles_creditos/editar"
  post "detalles_creditos/actualizar"
  get "detalles_creditos/index"

  #PRODUCCION
  get "produccion/index"
  get "produccion/lista"
  post "produccion/lista"
  get "produccion/agregar"
  post "produccion/guardar"
  get "produccion/eliminar"
  get "produccion/editar"
  post "produccion/actualizar"
  get "produccion/produccion_detalle_credito"
  get "produccion/produccion_detalle_debito"
  get "produccion/agregar_detalle_credito"
  get "produccion/agregar_detalle_debito"
  post "produccion/guardar_detalle_credito"
  post "produccion/guardar_detalle_debito"
  get "produccion/eliminar_produccion_detalle_credito"
  get "produccion/eliminar_produccion_detalle_debito"
  get "produccion/cambiar_estado_solicitado_a_en_progreso"
  get "produccion/cambiar_estado_en_progreso_a_finalizado"
  get "produccion/cambiar_estado_cobro"
  get "produccion/cambiar_estado_cobro_desconfirmar"
  get "produccion/planilla_resumen_produccion"
  get "produccion/planilla_resumen_produccion_pdf"
  get "produccion/planilla_resumen_produccion_cliente"
  get "produccion/planilla_resumen_produccion_cliente_pdf"
  
  #PACIENTES
  post "pacientes/lista"
  get "pacientes/lista"
  get "pacientes/agregar"
  post "pacientes/guardar"
  get "pacientes/eliminar"
  get "pacientes/editar"
  post "pacientes/actualizar"
  get "pacientes/index"
  get "pacientes/buscar_paciente"
  get "pacientes/buscar_persona"
  get "pacientes/buscar_paciente_cita"

  #PACIENTES DETALLES FONO
  get "pacientes_detalles_fono/paciente_detalle_fono"
  post "pacientes_detalles_fono/guardar_detalle_fono"

  #HISTORIALES PACIENTES
  post "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/index"
  get "historiales_pacientes/historial_paciente_detalle_fono"
  get "historiales_pacientes/lista_citas"
  post "historiales_pacientes/lista_citas"
  get "historiales_pacientes/historial_cita_detalle_fono_terminado"
  


  #PROFESIONALES
  post "profesionales/lista"
  get "profesionales/lista"
  get "profesionales/agregar"
  post "profesionales/guardar"
  get "profesionales/eliminar"
  get "profesionales/editar"
  post "profesionales/actualizar"
  get "profesionales/index"
  get "profesionales/buscar_profesional"
  get "profesionales/buscar_persona"
  
  

  #PRECIOS
  post "precios/lista"
  get "precios/lista"
  get "precios/agregar"
  post "precios/guardar"
  get "precios/eliminar"
  get "precios/editar"
  post "precios/actualizar"
  get "precios/index"
  get "precios/obtener_datos"
  get "precios/buscar_precio"
  get "precios/marcar_predeterminado"

  #CITAS
  get "citas/index"
  post "citas/lista"
  get "citas/lista"
  get "citas/agregar"
  post "citas/guardar"
  get "citas/editar"
  post "citas/actualizar"
  get "citas/eliminar"
  get "citas/cambiar_estado_cita_en_espera_a_en_consultorio"
  get "citas/cambiar_estado_cita_en_consultorio_a_terminado"
  get "citas/cambiar_estado_cobro_a_cobrado"
  get "citas/cambiar_estado_cobro_a_no_cobrado"
  get "citas/cambiar_estado_cita_terminado_a_en_consultorio"
  get "citas/postergar_cita"
  post "citas/guardar_postergar_cita"
  get "citas/imprimir_informe"
  get "citas/generar_informe_pdf"
  get "citas/cambiar_estado_cita_en_consultorio_a_en_espera"
  

  #CITAS DETALLES FONO
  get "citas_detalles_fono/cita_detalle_fono"
  post "citas_detalles_fono/guardar_cita_detalle_fono"
  get "citas_detalles_fono/emitir_resolucion"
  post "citas_detalles_fono/guardar_resolucion"
  get "citas_detalles_fono/adjuntar_resolucion"
  post "citas_detalles_fono/guardar_resolucion_adjunta"
  get "citas_detalles_fono/habilitar_descarga_archivo"
  get "citas_detalles_fono/deshabilitar_descarga_archivo"
  get "citas_detalles_fono/cita_detalle_fono_terminado"

#--------------------------------------------SISTEMA------------------------------------------------------------  
  #PERSONAS
  post "personas/lista"
  get "personas/lista"
  get "personas/agregar"
  get "personas/agregar_persona_senatics"
  post "personas/guardar"
  post "personas/guardar_persona_senatics"
  get "personas/eliminar"
  get "personas/editar"
  post "personas/actualizar"
  get "personas/index"
  get "personas/mostrar_formulario"
  post "personas/unificar_persona"
  get "personas/obtener_datos"
  get "personas/buscar_persona_senatics"
  get "personas/buscar_chofer"
  

  #ROLES
  post "roles/lista"
  get "roles/lista"
  get "roles/agregar"
  post "roles/guardar"
  get "roles/eliminar"
  get "roles/editar"
  post "roles/actualizar"
  get "roles/accesos"
  get "roles/agregar_acceso"
  get "roles/guardar_acceso"
  get "roles/eliminar_acceso"
  get "roles/index"

  
  #CONTROLADORES
  post "controladores/lista"
  get "controladores/lista"
  get "controladores/agregar"
  post "controladores/guardar"
  get "controladores/eliminar"
  get "controladores/editar"
  post "controladores/actualizar"
  get "controladores/acciones"
  get "controladores/agregar_accion"
  post "controladores/guardar_accion"
  get "controladores/eliminar_accion"
  get "controladores/index"

  
  #USUARIOS
  get "usuarios/cambiar_perfil_actual"
  get "usuarios/mi_cuenta"
  post "usuarios/actualizar_mi_cuenta"
  post "usuarios/actualizar_mi_password"
  get "usuarios/perfiles"
  get "usuarios/agregar_perfil"
  get "usuarios/guardar_perfil"
  get "usuarios/eliminar_perfil"
  post "usuarios/actualizar_password"
  get "usuarios/reset_password"
  get "usuarios/perfiles"
  get 'usuarios/index'
  get 'usuarios/lista'
  post 'usuarios/lista'
  get "usuarios/agregar"
  post "usuarios/guardar"
  get "usuarios/eliminar"
  get "usuarios/editar"
  post "usuarios/actualizar"
  get 'usuarios/buscar_persona'
  post 'usuarios/cambiar_estado_usuario'

  #LOGIN
  get 'login' => "usuarios_sessions#new",      :as => :login
  get 'logout' => "usuarios_sessions#destroy", :as => :logout
  post "usuarios_sessions/create"
  get "usuarios_sessions/acceso_denegado"
  get "usuarios_sessions/new"  
  get "usuarios_sessions/mantenimiento"  

  get "principal/buscar_institucion"
  get "principal/buscar_persona"
  get "principal/buscar_usuario"
  post "principal/guardar_recuperar_password"
  get "principal/recuperar_password"
  post "principal/guardar_usuario"
  get "principal/activar_cuenta"
  get "principal/agregar_usuario"
  get "contactos" => "principal#contactos", :as => :contactos
  get "index" => "principal#index", :as => :index
  get "about" => "principal#about", :as => :about
  get "legal" => "principal#legal", :as => :legal
  get "index" => "principal#index", :as => :indexv
	
	

  root 'principal#index'
  
  get "application/autocompletar" => 'application#autocompletar', :as => :autocompletar

  #INFORMACIONES
  get "informaciones/index"
  get "informaciones/lista"
  post "informaciones/lista"
	get "informaciones/perfiles"
	get "informaciones/enlaces"
  get "informaciones/agregar"
  post "informaciones/guardar"
	get "informaciones/agregar_enlace"
	get "informaciones/guardar_enlace"
	post "informaciones/guardar_enlace"
	get "informaciones/agregar_perfil"
  get "informaciones/guardar_perfil"
  get "informaciones/eliminar"
  get "informaciones/editar"
  post "informaciones/actualizar"
	get "informaciones/editar_enlace"
	post "informaciones/actualizar_enlace"
  get "informaciones/eliminar_enlace"

app/controllers/controladores_controller.rb
class ControladoresController < ApplicationController
  
  before_filter :require_usuario
  
  def index

  end

  def lista

    cond = []
    args = []

    if params[:form_buscar_controladores_id].present?

      cond << "id = ?"
      args << params[:form_buscar_controladores_id]

    end

    if params[:form_buscar_controladores_descripcion].present?

      cond << "descripcion ilike ?"
      args << "%#{quita_acentos(params[:form_buscar_controladores_descripcion])}%"

    end

    if cond.size > 0

      cond = cond.join(" and ").lines.to_a + args 
      @controladores = Controlador.ordenado_descripcion.where(cond).paginate(page: params[:page], per_page: 15)
      @total_encontrados = Controlador.where(cond).count

    else

      @controladores = Controlador.ordenado_descripcion.paginate(page: params[:page], per_page: 15)
      @total_encontrados = Controlador.count 

    end

    @total_registros = Controlador.count 

    respond_to do |f|

      f.js

    end

  end

  def agregar

    @controlador = Controlador.new

    respond_to do |f|
      f.js
    end

  end

  def guardar

    @valido = true
    @msg = ""

    @controlador = Controlador.new(params[:controlador])

    unless @controlador.descripcion.present?

      @valido = false
      @msg += "El campo descripcion no puede quedar vacio.<br />"

    end

    if @valido

      controlador = Controlador.where("descripcion = ?", @controlador.descripcion)

      if controlador.present?

        @valido = false
        @msg = "El controlador ya existe."

      end

    end

    if @valido

      if @controlador.save

        @controlador_ok = true

      else

        @msg = "ERROR: No se ha podido registrar."

      end

    end

    respond_to do |f|

      f.js

    end

  end

  def eliminar

    @controlador = Controlador.find(params[:id])

    if @controlador.destroy

      @eliminado = true

    end

  end

  def editar

    @controlador = Controlador.find(params[:id])

    respond_to do |f|

      f.js

    end

  end

  def actualizar

    @valido = true
    @msg = ""

    @controlador = Controlador.find(params[:controlador][:id])

    unless params[:controlador][:descripcion].present?

      @valido = false
      @msg += "El campo descripcion no puede quedar vacio."

    end

    if @valido

      controlador = Controlador.where("descripcion = ? and id <> ?", params[:controlador][:descripcion], @controlador.id )

      if controlador.present?

        @valido = false
        @msg = "El controlador ya existe."

      end

    end

    if @valido

      if @controlador.update_attributes(params[:controlador])

        @controlador_ok = true

      else

        @msg = "Error: No se ha podido actualizar el controlador."

      end

    end

    respond_to do |f|

      f.js

    end

  end

  def acciones

    @acciones = Accion.orden_id.where("controlador_id = ?", params[:controlador_id])

    respond_to do |f|

      f.js

    end
  
  end

  def agregar_accion

    @accion = Accion.new

    respond_to do |f|
      f.js
    end

  end

  def guardar_accion

    @valido = true
    @msg = ""

    @accion = Accion.new(params[:accion])

    unless @accion.controlador_id.present?

      @valido = false
      @msg += "El codigo del controlador no puede quedar vacio.<br />"

    end

    unless @accion.descripcion.present?

      @valido = false
      @msg += "El campo descripcion no puede quedar vacio.<br />"

    end

    if @valido

      accion_existente = Accion.where("controlador_id = ? and descripcion = ?", @accion.controlador_id, @accion.descripcion)

      if accion_existente.present?

        @valido = false
        @msg += "Esta acción ya existe."

      end

    end

    if @valido

      if @accion.save

        @accion_ok = true

      else

        @msg = "No se ha podido guardar la acción."

      end

    end

    respond_to do |f|

      f.js

    end

  end

  def eliminar_accion

    @accion = Accion.find(params[:id])
    @controlador_id = @accion.controlador_id

    if @accion.destroy

      @eliminado = true

    end

  end
  
end

app/helpers/controladores_helper.rb
module ControladoresHelper

  def link_to_editar_controlador(controlador)
    
    render :partial => 'link_to_editar_controlador', :locals => { :controlador => controlador}

  end

  def link_to_acciones_lista(controlador_id)
    
    render :partial => 'link_to_acciones_lista', :locals => { :controlador_id => controlador_id}

  end

  def link_to_acciones(controlador)

    render partial: "link_to_acciones", locals: { controlador: controlador}

  end

end

app/views/controladores/_agregar.html.erb
<%= javascript_include_tag "modulos/controladores.js" %>
<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar Controlador</h4>
      
    </div>

    <%= form_for @controlador, remote: true, url: controladores_guardar_url, html: { id: "form-agregar-controlador" } do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body">

        <div class="panel-body">
      
          <div class="col-sm-4"><%= label_tag nil, "Descripci&oacute;n #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :descripcion, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />
  
        </div>

        
      </div>
      
      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Guardar", class: "btn btn-primary", id: "btn-guardar-controlador" %>
          
      </div>
    
    <% end %>

  </div>
</div>

<style type="text/css">

  #form-agregar-controlador label, #form-agregar-controlador input[type='text'] { float:left; margin-top:5px;}
  #form-agregar-controlador br {clear:both; }
  #form-agregar-controlador label { width:200px; font-size:12px;}

</style>

<script type="text/javascript">

  setTimeout(function(){ $("#controlador_descripcion").focus(); }, 1000);

</script>

app/views/controladores/_agregar_accion.html.erb
<%= javascript_include_tag "modulos/controladores.js" %>
<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar Acci&oacute;n</h4>
      
    </div>

    <%= form_for @accion, remote: true, url: controladores_guardar_accion_url, html: { id: "form-agregar-accion" } do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>
      <%= f.hidden_field :controlador_id, :value => params[:controlador_id]%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Descripci&oacute;n #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :descripcion, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />
  
        </div>
        
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Guardar", class: "btn btn-primary", id: "btn-guardar-accion" %>
          
      </div>

    <% end %>

  </div>
</div>

<style type="text/css">

  #form-agregar-accion label, #form-agregar-accion input[type='text'] { float:left; margin-top:5px;}
  #form-agregar-accion br {clear:both; }
  #form-agregar-accion label { width:200px;font-size:12px;}

</style>

<script type="text/javascript">

  setTimeout(function(){ $("#accion_descripcion").focus(); }, 1000);

</script>

app/views/controladores/_editar.html.erb
<%= javascript_include_tag "modulos/controladores.js" %>
<div class="modal-dialog" style="text-align:left;">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Editar Controlador</h4>
      
    </div>

    <%= form_for @controlador, remote: true, url: controladores_actualizar_url, html: { id: "form-editar-controlador" }, method: 'POST' do |f| %>

      <%= f.hidden_field :id %>
      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Descripci&oacute;n #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :descripcion, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />
 
        </div>
            
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Actualizar", class: "btn btn-primary", id: "btn-actualizar-controlador" %>
          
      </div>

    <% end %>
  </div>
</div>

<style type="text/css">

  #form-editar-controlador label, #form-editar-controlador input[type='text'] { float:left; margin-top:5px;}
  #form-editar-controlador br {clear:both; }
  #form-editar-controlador label { width:200px; font-size:12px;}

</style>

<script type="text/javascript">

  setTimeout(function(){ $("#controlador_descripcion").focus(); }, 1000);

</script>

app/views/controladores/_link_to_acciones.html.erb
<%= link_to "<i class='glyphicon glyphicon-th-list'></i>".html_safe, "#", id: "link-to-acciones-#{controlador.id}", class: 'btn btn-info btn-xs', title: 'Haga click para ver las acciones.' %>

<script type="text/javascript">

  $("#link-to-acciones-<%= controlador.id %>").bind('click', function(){

    var contenido = $.trim($("#acciones-<%= controlador.id %>").html());

    $(".acciones").html('');

    if(contenido.length == 0){

    $(this).parent().parent().after("<tr id='acciones-<%= controlador.id %>' class='acciones'><td colspan='4' style='text-align:center;'><i class='fa fa-refresh fa-spin'></i> Cargando...</td></tr>")

      $.ajax({

        type: 'GET',
        url: '<%= url_for(controladores_acciones_path) %>',  
        data: { controlador_id: <%= controlador.id %>},
        dataType: 'script'
        
      })

    }
    
    return false;
  })

</script>

app/views/controladores/_link_to_editar_controlador.html.erb
<%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, "#", id: "link-to-editar-controlador-#{controlador.id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar el controlador.' %>

<%= modal_window( window_id: "modal-window-editar-controlador", link_to_id: "#link-to-editar-controlador-#{controlador.id}", url: controladores_editar_path( window_id: "modal-window-editar-controlador", id: controlador.id) )%>

app/views/controladores/_lista.html.erb
<% if controladores.present? %>

  <% controladores.each do |c| %>

    <tr>

      <td style="width:100px;"><%= c.id %></td>
      <td><%= c.descripcion %></td>
      <td></td>
      <td style="text-align:center;">
        <%= link_to_acciones(c) %>
        <%= link_to_editar_controlador(c) %>
        <%= link_to icon_eliminar, controladores_eliminar_path(id: c.id), remote: true, class: "btn btn-danger btn-xs", title: 'Haga click para eliminar el controlador', data: { confirm: "Esta seguro de eliminar el controlador ?"} %> 
      </td>

    </tr>

  <% end %>

<% else %>

  <tr>

    <td colspan="4"><p class='none-result'>No se han encontrado resultados.</p></td>

  </tr>

<% end %>

app/views/controladores/actualizar.js.erb
<% if @controlador_ok.present? %>

   $("<div class='col-sm-12' id='msg-editar-controlador' style='color:#000;padding-top:5px;font-size:10px;background:#d6ffd6;border-radius:5px;text-align:center;'>Actualizado Exitosamente.</div>").insertBefore("#form-editar-controlador");
   
  $("#form_buscar_controladores_id").val('<%= @controlador.id %>');
  $("#form_buscar_controladores_descripcion").val(''); 
  setTimeout(function(){ $("#<%= params[:window_id]%>").modal('hide'); $("#form-buscar-controladores").submit(); }, 3000);

<% else %>

  $("<div class='col-sm-12' id='msg-editar-controlador' style='color:#000;padding-top:5px;font-size:10px;background: #f8dfdf;border-radius:5px;text-align:center;'><%= @msg.html_safe %></div>").insertBefore("#form-editar-controlador");

<% end %>

app/views/controladores/agregar.js.erb
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'agregar')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/controladores/agregar_accion.js.erb
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'agregar_accion')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/controladores/editar.js.erb
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'editar')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/controladores/eliminar.js.erb
<% if @eliminado %>

   $("<div class='col-sm-12' id='msg-eliminar-controlador' style='color:#000;padding-top:5px;font-size:10px;background:#d6ffd6;border-radius:5px;text-align:center;'>Eliminado exitosamente.</div>").insertBefore("#table-controladores");
   $("#form-buscar-controladores").submit();
    setTimeout(function(){ $("#msg-eliminar-controlador").remove(); }, 3000);

<% else %>

  $("<div class='col-sm-12' id='msg-eliminar-controlador' style='color:#000;padding-top:5px;font-size:10px;background: #f8dfdf;border-radius:5px;text-align:center;'>No se ha podido eliminar el controlador.</div>").insertBefore("#table-controladores");
  setTimeout(function(){ $("#msg-eliminar-controlador").remove(); }, 3000);

<% end %>

app/views/controladores/eliminar_accion.js.erb
<% if @eliminado %>

   $("<div class='col-sm-12' id='msg-eliminar-accion' style='color:#000;padding-top:5px;font-size:10px;background:#d6ffd6;border-radius:5px;text-align:center;'>Eliminado exitosamente.</div>").insertBefore("#table-acciones");

  setTimeout(function(){ 
    $("#msg-eliminar-accion").remove(); 
    $("#link-to-acciones-<%= @controlador_id %>").trigger('click');
    $("#link-to-acciones-<%= @controlador_id %>").trigger('click');
   }, 3000);

<% else %>

  $("<div class='col-sm-12' id='msg-eliminar-accion' style='color:#000;padding-top:5px;font-size:10px;background: #f8dfdf;border-radius:5px;text-align:center;'>No se ha podido eliminar la acción.</div>").insertBefore("#table-acciones");
  setTimeout(function(){ $("#msg-eliminar-accion").remove(); }, 3000);

<% end %>

app/views/controladores/guardar.js.erb
<% if @controlador_ok.present? %>

   $("<div class='col-sm-12' id='msg-agregar-controlador' style='color:#000;padding-top:5px;font-size:10px;background:#d6ffd6;border-radius:5px;text-align:center;'>Registrado Exitosamente.</div>").insertBefore("#form-agregar-controlador");
   
  $("#form_buscar_controladores_id").val('<%= @controlador.id %>');
  $("#form_buscar_controladores_descripcion").val('');
  $("#form-buscar-controladores").submit();
  setTimeout(function(){ $("#<%= params[:window_id]%>").modal('hide'); }, 3000);

<% else %>

  $("<div class='col-sm-12' id='msg-agregar-controlador' style='color:#000;padding-top:5px;font-size:10px;background: #f8dfdf;border-radius:5px;text-align:center;'><%= @msg.html_safe %></div>").insertBefore("#form-agregar-controlador");

<% end %>

app/views/controladores/lista.js.erb
$("#controladores-lista").html("<%= escape_javascript(render :partial => "lista", :locals => { controladores: @controladores }) %>");
$("#controladores-footer").html("<%= escape_javascript(render :partial => "footer", :locals => { controladores: @controladores }) %>");