config/routes.rb
  get "tutores/buscar_persona" 
  get "tutores/tutor_detalle"
  get "tutores/agregar_tutor_detalle"
  post "tutores/guardar_tutor_detalle"
  get "tutores/eliminar_tutor_detalle"
  
  #CARGOS
  post 'cargos/lista'
  get 'cargos/lista'
  get 'cargos/agregar'
  post 'cargos/guardar'
  get 'cargos/eliminar'
  get 'cargos/editar'
  post 'cargos/actualizar'
  get 'cargos/index'

  #REMUNERACIONES EXTRAS
  post 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/agregar'
  post 'pagos_remuneraciones_extras/guardar'
  get 'pagos_remuneraciones_extras/eliminar'
  get 'pagos_remuneraciones_extras/editar'
  post 'pagos_remuneraciones_extras/actualizar'
  get 'pagos_remuneraciones_extras/index'

#DESCUENTOS
  post 'pagos_descuentos/lista'
  get 'pagos_descuentos/lista'
  get 'pagos_descuentos/agregar'
  post 'pagos_descuentos/guardar'
  get 'pagos_descuentos/eliminar'
  get 'pagos_descuentos/editar'
  post 'pagos_descuentos/actualizar'
  get 'pagos_descuentos/index'

#ADELANTOS
  post 'pagos_adelantos/lista'
  get 'pagos_adelantos/lista'
  get 'pagos_adelantos/agregar'
  post 'pagos_adelantos/guardar'
  get 'pagos_adelantos/eliminar'
  get 'pagos_adelantos/editar'
  post 'pagos_adelantos/actualizar'
  get 'pagos_adelantos/index'

#PAGOS DE SALARIOS
  get 'pagos_salarios/index'
  post 'pagos_salarios/lista'
  get 'pagos_salarios/lista'
  get 'pagos_salarios/agregar'
  post 'pagos_salarios/guardar'
  get 'pagos_salarios/eliminar'
  get 'pagos_salarios/salario_detalle'

  #ADELANTOS
  post 'registros_gastos/lista'
  get 'registros_gastos/lista'
  get 'registros_gastos/agregar'
  post 'registros_gastos/guardar'
  get 'registros_gastos/eliminar'
  get 'registros_gastos/editar'
  post 'registros_gastos/actualizar'
  get 'registros_gastos/index'
#---------------------------------------FONOWARE------------------------------------------------------------------------    
  #CRONTAB
  get "crontab_ultron/index"

  #JURISDICCIONES
  get "jurisdicciones/index"
  get "jurisdicciones/buscar_juridisccion_oferta" 

  #INFORMES
  get "informes/index"
  get "informes/index_gastos"
  get "informes/index_balance"
  get "informes/indexa"
  get "informes/generar_pdf"

  #DETALLES DEBITOS
  post "detalles_debitos/lista"
  get "detalles_debitos/lista"
  get "detalles_debitos/agregar"
  post "detalles_debitos/guardar"
  get "detalles_debitos/eliminar"
  get "detalles_debitos/editar"
  post "detalles_debitos/actualizar"
  get "detalles_debitos/index"
 
  #DETALLES CREDITOS
  post "detalles_creditos/lista"
  get "detalles_creditos/lista"
  get "detalles_creditos/agregar"
  post "detalles_creditos/guardar"
  get "detalles_creditos/eliminar"
  get "detalles_creditos/editar"
  post "detalles_creditos/actualizar"
  get "detalles_creditos/index"

  #PRODUCCION
  get "produccion/index"
  get "produccion/lista"
  post "produccion/lista"
  get "produccion/agregar"
  post "produccion/guardar"
  get "produccion/eliminar"
  get "produccion/editar"
  post "produccion/actualizar"
  get "produccion/produccion_detalle_credito"
  get "produccion/produccion_detalle_debito"
  get "produccion/agregar_detalle_credito"
  get "produccion/agregar_detalle_debito"
  post "produccion/guardar_detalle_credito"
  post "produccion/guardar_detalle_debito"
  get "produccion/eliminar_produccion_detalle_credito"
  get "produccion/eliminar_produccion_detalle_debito"
  get "produccion/cambiar_estado_solicitado_a_en_progreso"
  get "produccion/cambiar_estado_en_progreso_a_finalizado"
  get "produccion/cambiar_estado_cobro"
  get "produccion/cambiar_estado_cobro_desconfirmar"
  get "produccion/planilla_resumen_produccion"
  get "produccion/planilla_resumen_produccion_pdf"
  get "produccion/planilla_resumen_produccion_cliente"
  get "produccion/planilla_resumen_produccion_cliente_pdf"
  
  #PACIENTES
  post "pacientes/lista"
  get "pacientes/lista"
  get "pacientes/agregar"
  post "pacientes/guardar"
  get "pacientes/eliminar"
  get "pacientes/editar"
  post "pacientes/actualizar"
  get "pacientes/index"
  get "pacientes/buscar_paciente"
  get "pacientes/buscar_persona"
  get "pacientes/buscar_paciente_cita"

  #PACIENTES DETALLES FONO
  get "pacientes_detalles_fono/paciente_detalle_fono"
  post "pacientes_detalles_fono/guardar_detalle_fono"

  #HISTORIALES PACIENTES
  post "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/index"
  get "historiales_pacientes/historial_paciente_detalle_fono"
  get "historiales_pacientes/lista_citas"
  post "historiales_pacientes/lista_citas"
  get "historiales_pacientes/historial_cita_detalle_fono_terminado"
  


  #PROFESIONALES
  post "profesionales/lista"
  get "profesionales/lista"
  get "profesionales/agregar"
  post "profesionales/guardar"
  get "profesionales/eliminar"
  get "profesionales/editar"
  post "profesionales/actualizar"
  get "profesionales/index"
  get "profesionales/buscar_profesional"
  get "profesionales/buscar_persona"
  
  

  #PRECIOS
  post "precios/lista"
  get "precios/lista"
  get "precios/agregar"
  post "precios/guardar"
  get "precios/eliminar"
  get "precios/editar"
  post "precios/actualizar"
  get "precios/index"
  get "precios/obtener_datos"
  get "precios/buscar_precio"
  get "precios/marcar_predeterminado"

  #CITAS
  get "citas/index"
  post "citas/lista"
  get "citas/lista"
  get "citas/agregar"
  post "citas/guardar"
  get "citas/editar"
  post "citas/actualizar"
  get "citas/eliminar"
  get "citas/cambiar_estado_cita_en_espera_a_en_consultorio"
  get "citas/cambiar_estado_cita_en_consultorio_a_terminado"
  get "citas/cambiar_estado_cobro_a_cobrado"
  get "citas/cambiar_estado_cobro_a_no_cobrado"
  get "citas/cambiar_estado_cita_terminado_a_en_consultorio"
  get "citas/postergar_cita"
  post "citas/guardar_postergar_cita"
  get "citas/imprimir_informe"
  get "citas/generar_informe_pdf"
  get "citas/cambiar_estado_cita_en_consultorio_a_en_espera"
  

  #CITAS DETALLES FONO
  get "citas_detalles_fono/cita_detalle_fono"
  post "citas_detalles_fono/guardar_cita_detalle_fono"
  get "citas_detalles_fono/emitir_resolucion"
  post "citas_detalles_fono/guardar_resolucion"
  get "citas_detalles_fono/adjuntar_resolucion"
  post "citas_detalles_fono/guardar_resolucion_adjunta"
  get "citas_detalles_fono/habilitar_descarga_archivo"
  get "citas_detalles_fono/deshabilitar_descarga_archivo"
  get "citas_detalles_fono/cita_detalle_fono_terminado"

#--------------------------------------------SISTEMA------------------------------------------------------------  
  #PERSONAS
  post "personas/lista"
  get "personas/lista"
  get "personas/agregar"
  get "personas/agregar_persona_senatics"
  post "personas/guardar"
  post "personas/guardar_persona_senatics"
  get "personas/eliminar"
  get "personas/editar"
  post "personas/actualizar"
  get "personas/index"
  get "personas/mostrar_formulario"
  post "personas/unificar_persona"
  get "personas/obtener_datos"
  get "personas/buscar_persona_senatics"
  get "personas/buscar_chofer"
  

  #ROLES
  post "roles/lista"
  get "roles/lista"
  get "roles/agregar"
  post "roles/guardar"
  get "roles/eliminar"
  get "roles/editar"
  post "roles/actualizar"
  get "roles/accesos"
  get "roles/agregar_acceso"
  get "roles/guardar_acceso"
  get "roles/eliminar_acceso"
  get "roles/index"

  
  #CONTROLADORES
  post "controladores/lista"
  get "controladores/lista"
  get "controladores/agregar"
  post "controladores/guardar"
  get "controladores/eliminar"
  get "controladores/editar"
  post "controladores/actualizar"
  get "controladores/acciones"
  get "controladores/agregar_accion"
  post "controladores/guardar_accion"
  get "controladores/eliminar_accion"
  get "controladores/index"

  
  #USUARIOS
  get "usuarios/cambiar_perfil_actual"
  get "usuarios/mi_cuenta"
  post "usuarios/actualizar_mi_cuenta"
  post "usuarios/actualizar_mi_password"
  get "usuarios/perfiles"
  get "usuarios/agregar_perfil"
  get "usuarios/guardar_perfil"
  get "usuarios/eliminar_perfil"
  post "usuarios/actualizar_password"
  get "usuarios/reset_password"
  get "usuarios/perfiles"
  get 'usuarios/index'
  get 'usuarios/lista'
  post 'usuarios/lista'
  get "usuarios/agregar"
  post "usuarios/guardar"
  get "usuarios/eliminar"
  get "usuarios/editar"
  post "usuarios/actualizar"
  get 'usuarios/buscar_persona'
  post 'usuarios/cambiar_estado_usuario'

  #LOGIN
  get 'login' => "usuarios_sessions#new",      :as => :login
  get 'logout' => "usuarios_sessions#destroy", :as => :logout
  post "usuarios_sessions/create"
  get "usuarios_sessions/acceso_denegado"
  get "usuarios_sessions/new"  
  get "usuarios_sessions/mantenimiento"  

  get "principal/buscar_institucion"
  get "principal/buscar_persona"
  get "principal/buscar_usuario"
  post "principal/guardar_recuperar_password"
  get "principal/recuperar_password"
  post "principal/guardar_usuario"
  get "principal/activar_cuenta"
  get "principal/agregar_usuario"
  get "contactos" => "principal#contactos", :as => :contactos
  get "index" => "principal#index", :as => :index
  get "about" => "principal#about", :as => :about
  get "legal" => "principal#legal", :as => :legal
  get "index" => "principal#index", :as => :indexv
	
	

  root 'principal#index'
  
  get "application/autocompletar" => 'application#autocompletar', :as => :autocompletar

  #INFORMACIONES
  get "informaciones/index"
  get "informaciones/lista"
  post "informaciones/lista"
	get "informaciones/perfiles"
	get "informaciones/enlaces"
  get "informaciones/agregar"
  post "informaciones/guardar"
	get "informaciones/agregar_enlace"
	get "informaciones/guardar_enlace"
	post "informaciones/guardar_enlace"
	get "informaciones/agregar_perfil"
  get "informaciones/guardar_perfil"
  get "informaciones/eliminar"
  get "informaciones/editar"
  post "informaciones/actualizar"
	get "informaciones/editar_enlace"
	post "informaciones/actualizar_enlace"
  get "informaciones/eliminar_enlace"

app/models/cita.rb
class Cita < ActiveRecord::Base

  self.table_name="citas"
  self.primary_key="id"
  
  attr_accessible :id, :fecha_cita, :paciente_id, :profesional_id, :tipo_consulta_id, :especialidad_id, :precio_id, :observacion, :created_at, :updated_at
  
  scope :orden_01, -> { order("id")}
  scope :fonoaudiologia, -> { where("especialidad_id = ?", PARAMETRO[:especialidad_fonoaudiologia])}
  
end

app/helpers/citas_helper.rb
module CitasHelper

  def link_to_editar_cita(cita)

      render partial: 'link_to_editar_cita', locals: { cita: cita }
      
  end

  def link_to_cita_detalle_fono(cita_id)

    render partial: 'link_to_cita_detalle_fono', locals: { cita_id: cita_id}

  end

  def link_to_cita_detalle_fono_terminado(cita_id)

    render partial: 'link_to_cita_detalle_fono_terminado', locals: { cita_id: cita_id}

  end

  
end

app/views/citas/_agregar.html.erb
<%= javascript_include_tag "modulos/pacientes.js" %>
<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar nueva Cita</h4>
      
    </div>

    <%= form_for @cita, remote: true, url: citas_guardar_url, html: { id: "form-agregar-cita" }, method: 'POST' do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body">

        <div class="panel-body">
 
          <div class="col-sm-4"><%= label_tag :nil, "Fecha Cita #{attr_requerido}".html_safe %></div>

          <div class='input-group date'>
          <%= text_field_tag :fecha_cita, nil, class: 'form-control input-sm' %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
          </div>

          <div class="col-sm-1"></div><br /> 

          <div class="col-sm-4"><%= label_tag nil, "Paciente #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= hidden_field_tag :paciente_id, nil ,class: 'form-control input-sm' %></div>
          <div class="col-sm-7"><%= text_area_tag :cita_paciente_id,nil ,rows: 2,class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Profesional #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= hidden_field_tag :profesional_id, nil ,class: 'form-control input-sm' %></div>
          <div class="col-sm-7"><%= text_area_tag :cita_profesional_id,nil ,rows: 2,class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= f.label :tipo_consulta, "Tipo Consulta #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.collection_select :tipo_consulta_id, TipoConsulta.especialidad_fonoaudiologia, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm', style: "width:220px;"} %></div>
          <div class="col-sm-1"></div><br />
          <div class="col-sm-1"></div><br />

           <div class="col-sm-4"><%= f.label :monto_consulta, "Monto Consulta #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.collection_select :precio_id, VPrecio.predeterminado, :id, :descripcion, { include_blank: false}, {class: 'form-control input-sm', style: "width:220px;"} %></div>
          <div class="col-sm-1"></div><br />
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Observación".html_safe %></div>
          <div class="col-sm-7"><%= text_area_tag :observacion,nil ,:size =>"25x5",class: 'form-control input-sm', maxlength: 255 %></div>
          <div class="col-sm-1"></div><br />


        </div>  
       
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">
        <%= link_to "<span class='glyphicon glyphicon-remove'></span> Cerrar".html_safe, "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
         <%= link_to "Guardar","#" ,class: "btn btn-primary", id: "btn-guardar-cita" %>
      </div>

    <% end %>

  </div>
  
</div>

<style type="text/css">

  #form-agregar-cita label, #form-agregar-cita input[type='text'], #form-agregar-cita select { float:left; margin-top:5px;}
  #form-agregar-cita br {clear:both; }
  #form-agregar-cita label { width:200px;font-size:12px;margin-top:10px;}
  .ui-autocomplete{z-index: 1000000; font-size: 10px;}
  

</style>

<script type="text/javascript">

  aplicar_datepicker2();

  

  $("#fecha_cita").bind('change', function(){   

    var personas = [];
    $("#cita_profesional_id").val('');
    $("#profesional_id").val('');
    $("#cita_profesional_id").attr('readonly', false);

    $.getJSON("<%= url_for(profesionales_buscar_profesional_path) %>", { nombre_profesional: $("#cita_profesional_id").val()}, function(j){
        
      var nombre_persona = "";
      var options = "<option value=''> -- Seleccione un Profesional -- </option>"

      for (var i = 0; i < j.length; i++) {
        
        if(j[i].nombre_persona != nombre_persona ){
          
          personas.push( {value: j[i].profesional_id +" - "+ j[i].nombre_persona+" "+j[i].apellido_persona });
          nombre_persona =j[i].profesional_id +" - "+ j[i].nombre_persona+" "+j[i].apellido_persona ;

          options += "<option value="+ j[i].profesional_id +" - "+ j[i].nombre_persona+" "+j[i].apellido_persona + "</option>"

        }

      }

      $("#chofer_id").html(options);

    })

    $("#cita_profesional_id").autocomplete({

      minLength: 1,
      source: personas,
      focus: function( event, ui ) {
      
        $("#cita_profesional_id" ).val( ui.item.label );
        return false;
      },
      select: function( event, ui ) {

        var datos = ui.item.value.split(" - ");
        $("#cita_profesional_id").val( ui.item.label );
        $("#profesional_id").val(datos[0]);
        return false;
      }
    })

  });


  $("#fecha_cita").bind('change', function(){   

    var personas = [];
    $("#cita_paciente_id").val('');
    $("#paciente_id").val('');
    $("#cita_paciente_id").attr('readonly', false);

    $.getJSON("<%= url_for(pacientes_buscar_paciente_cita_path) %>", { nombre_paciente: $("#cita_paciente_id").val()}, function(j){
        
      var nombre_persona = "";
      var options = "<option value=''> -- Seleccione un Profesional -- </option>"

      for (var i = 0; i < j.length; i++) {
        
        if(j[i].nombre_persona != nombre_persona ){
          
          personas.push( {value: j[i].paciente_id +" - "+ j[i].nombre_persona+" "+j[i].apellido_persona });
          nombre_persona =j[i].paciente_id +" - "+ j[i].nombre_persona+" "+j[i].apellido_persona ;

          options += "<option value="+ j[i].paciente_id +" - "+ j[i].nombre_persona+" "+j[i].apellido_persona + "</option>"

        }

      }

      $("#chofer_id").html(options);

    })

    $("#cita_paciente_id").autocomplete({

      minLength: 1,
      source: personas,
      focus: function( event, ui ) {
      
        $("#cita_paciente_id" ).val( ui.item.label );
        return false;
      },
      select: function( event, ui ) {

        var datos = ui.item.value.split(" - ");
        $("#cita_paciente_id").val( ui.item.label );
        $("#paciente_id").val(datos[0]);
        return false;

      }
    })

  });

  $("textarea").keydown(function(e){
    // Enter was pressed without shift key
    if (e.keyCode == 13 && !e.shiftKey)
    {
        // prevent default behavior
        e.preventDefault();
    }
    });



  $("#btn-guardar-cita").bind('click', function () {

      valido = true
      msg = ""

      if($("#fecha_cita").val().length == 0){

        msg +="Ingrese la fecha de la Cita.\n"
        valido = false
      
      }

      if($("#paciente_id").val().length == 0){

        msg +="Debe ingresar un paciente.\n"
        valido = false
      
      }

      if($("#profesional_id").val().length == 0){

        msg +="Debe ingresar un profesional.\n"
        valido = false
      
      }

      if($("#cita_tipo_consulta_id").val().length == 0){

        msg +="Debe seleccionar el tipo de consulta.\n"
        valido = false
      
      }

      if($("#cita_precio_id").val().length == 0){

        msg +="Debe seleccionar el monto de la consulta.\n"
        valido = false
      
      }

      if (valido){

        swal({
          title: "Confirmar",
          text: "Al confirmar se registrará la cita en la fecha seleccionada con el estado En Espera",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

            $("#form-agregar-cita").submit();
            
          } 

        });

      }else{

        swal(msg);
      
      }

      return false;
    
    })


</script>

app/views/citas/_detalles_planilla_resumen_cita.pdf.erb
<table align="center" class="cual" style="width: 80%; border: 1px solid #000 !important;">
 
  

  <% cita_detalle = CitaDetalleFono.where("cita_id = ?", @cita.cita_id).first %>
  
  <%if  cita_detalle.present?%>
    
    <tr>

        <th>Objetivos</th>

    </tr>
    
    <tr>

      <td align="left"><%= text_area_tag :objetivo,cita_detalle.objetivo.gsub('<br/>',"\r\n"), :size =>"150x15",  class: 'form-control input-sm' ,maxlength: "510", style: "border: none;"%></td>

    </tr> 

    <tr><td></td></tr>

    <tr>

        <th>Resultados</th>
        
    </tr>
     <tr>

        <td align="left"><%= text_area_tag :objetivo,cita_detalle.resultado.gsub('<br/>',"\r\n"), :size =>"150x20",  class: 'form-control input-sm' ,maxlength: "510", style: "border: none;"%></td>

      </tr>  
      <tr><td></td></tr>
      <tr>

        <th>Observaciones</th>
        
    </tr>
    <tr>

        <td align="left"><%= text_area_tag :objetivo,cita_detalle.observacion.gsub('<br/>',"\r\n"), :size =>"150x15",  class: 'form-control input-sm' ,maxlength: "510", style: "border: none;"%></td>

    </tr>      
    <tr><td></td></tr>
<%end%>

app/views/citas/_link_to_cita_detalle_fono.html.erb
<%= link_to icon_detalles, "#", id: "link-to-cita-detalle-fono-#{cita_id}", class: 'btn btn-success btn-xs', title: 'Haga click para agregar detalles a la cita', onclick: "$('.modal').html('');return false;" %>

<script type="text/javascript">

  $("#link-to-cita-detalle-fono-<%= cita_id %>").bind('click', function(){

    var contenido = $.trim($("#cita-detalle-fono-<%= cita_id %>").html());

    $(".cita-detalle-fono").html('');

    if(contenido.length == 0){

    $(this).parent().parent().after("<tr id='cita-detalle-fono-<%= cita_id %>' class='cita-detalle-fono'><td colspan='4' style='text-align:center;'><i class='fa fa-refresh fa-spin'></i> Cargando...</td></tr>")

      $.ajax({

        type: 'GET',
        url: '<%= url_for(citas_detalles_fono_cita_detalle_fono_path) %>',  
        data: { cita_id: <%= cita_id %>},
        dataType: 'script'
        
      })

    }
    
    return false;
  })

</script>

app/views/citas/_postergar_cita.html.erb
<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Postergar Cita</h4>
      
    </div>

    <%= form_for @cita, remote: true, url: citas_guardar_postergar_cita_url, html: { id: "form-modificar-cita" }, method: 'POST' do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>
      <%= hidden_field_tag :cita_id, params[:cita_id]%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag :nil, "Fecha Cita #{attr_requerido}".html_safe %></div>

          <div class='input-group date'>
          <%= text_field_tag :fecha_cita, nil, class: 'form-control input-sm' %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
          </div>

          <div class="col-sm-1"></div><br /> 

          <div class="col-sm-4"><%= label_tag nil, "Motivo/Observación #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= text_area_tag :observacion,nil ,:size =>"25x5",class: 'form-control input-sm', maxlength: 255 %></div>
          <div class="col-sm-1"></div><br />


        </div>  
       
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">
        <%= link_to "<span class='glyphicon glyphicon-remove'></span> Cerrar".html_safe, "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
         <%= link_to "Guardar","#" ,class: "btn btn-primary", id: "btn-guardar-postergar-cita" %>
      </div>

    <% end %>

  </div>
  
</div>

<style type="text/css">

  #form-modificar-cita label, #form-modificar-cita input[type='text'], #form-modificar-cita select { float:left; margin-top:5px;}
  #form-modificar-cita br {clear:both; }
  #form-modificar-cita label { width:200px;font-size:12px;margin-top:10px;}
  .ui-autocomplete{z-index: 1000000; font-size: 10px;}
  

</style>

<script type="text/javascript">

  aplicar_datepicker2();


  $("#btn-guardar-postergar-cita").bind('click', function () {

      valido = true
      msg = ""
      
      if($("#fecha_cita").val().length == 0){

        msg +="Ingrese la fecha de la Cita.\n"
        valido = false
      
      }

      if($("#observacion").val().length == 0){

        msg +="El campo motivo no puede estar vacío.\n"
        valido = false
      
      }

      if (valido){

        swal({
          title: "Confirmar",
          text: "Al confirmar se registrará la cita en la fecha seleccionada con el estado de Cita Postergado",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

            $("#<%= params[:window_id]%>").modal('hide');
            $("#form-modificar-cita").submit();
            
          } 

        });

      }else{

        swal(msg);
      
      }

      return false;
    
    })


</script>

app/views/citas/cambiar_estado_cita_en_consultorio_a_en_espera.js.erb
<% if @actualizado %>
  
  $("#form_buscar_citas_id").val('<%= @cita.id %>');
  $("#form-buscar-citas").submit();

  setTimeout(function(){ 

    swal({title: "Atención", text: "<%= j(@msg)%>", html: false})
    
  }, 2000);

<% else %>

    swal({title: "Atención", text: "<%= j(@msg)%>", html: false})

<% end %>

app/views/citas/imprimir_informe.js.erb
<%if @cita.present?%>

  
  setTimeout(function(){ 

    swal("Resumen generado Exitosamente!", "", "success");

  }, 
  1000);
  
  
    window.open("<%= url_for(citas_generar_informe_pdf_path(@parametros))%>", '_blank')
  

<%else%>

  setTimeout(function(){ 

    swal("No se pudo generar el Resumen. Intente más tarde", "","warning");

  }, 1000);

<%end%>

app/views/citas/lista.js.erb
$("#citas-lista").html("<%= escape_javascript(render partial: "lista", locals: { citas: @citas }) %>");