config/routes.rb
Rails.application.routes.draw do

  
  namespace 'api' do
    namespace 'v1' do
  
      resources :personas
      resources :usuarios
  
    end
  end  

# Avatar routes
get "avatar/:size/:background/:text" => Dragonfly.app.endpoint { |params, app|
  app.generate(:initial_avatar, URI.unescape(params[:text]), { size: params[:size], background_color: params[:background] })
}, as: :avatar

#-------------------------------------MONIGOTE----------------------------------------------------

#GENERACION DE CUOTAS
  get 'cuotas/index'
  post 'cuotas/lista'
  get 'cuotas/lista'
  get 'cuotas/agregar'
  post 'cuotas/guardar'
  get 'cuotas/eliminar'
  get 'cuotas/cuota_detalle'
  post 'cuotas/lista_cuota_detalle'
  get 'cuotas/lista_cuota_detalle'
  get 'cuotas/pagar_cuota_detalle'
  post 'cuotas/guardar_pago_cuota_detalle'
  get 'cuotas/index_detalles'
  post 'cuotas/lista_cuotas_detalles'
  get 'cuotas/lista_cuotas_detalles'
  get 'cuotas/notificar_cuota_pendiente'


#PERSONALES
  post 'personales/lista'
  get 'personales/lista'
  get 'personales/agregar'
  post 'personales/guardar'
  get 'personales/eliminar'
  get 'personales/editar'
  post 'personales/actualizar'
  get 'personales/index'
  get 'personales/buscar_personal'
  
#MATRICULACIONES
  get "matriculaciones/index"
  post "matriculaciones/lista"
  get "matriculaciones/lista"
  get "matriculaciones/agregar"
  post "matriculaciones/guardar"
  get "matriculaciones/editar"
  post "matriculaciones/actualizar"
  get "matriculaciones/eliminar"
  get "matriculaciones/matriculacion_detalle"
  get "matriculaciones/agregar_matriculacion_detalle"
  post "matriculaciones/guardar_matriculacion_detalle"
  get "matriculaciones/eliminar_matriculacion_detalle"
 

#ALUMNOS
  post "alumnos/lista"
  get "alumnos/lista"
  get "alumnos/agregar"
  post "alumnos/guardar"
  get "alumnos/eliminar"
  get "alumnos/editar"
  post "alumnos/actualizar"
  get "alumnos/index"
  get "alumnos/buscar_alumno"
  get "alumnos/buscar_persona" 
  get "alumnos/buscar_alumno_documento"
  get "alumnos/alumno_detalle"
  post "alumnos/guardar_alumno_detalle"
  get "alumnos/alumno_informe"
  get "alumnos/agregar_alumno_informe"
  post "alumnos/guardar_alumno_informe"
  get "alumnos/eliminar_alumno_informe"

#TUTORES
  post "tutores/lista"
  get "tutores/lista"
  get "tutores/agregar"
  post "tutores/guardar"
  get "tutores/eliminar"
  get "tutores/editar"
  post "tutores/actualizar"
  get "tutores/index"
  get "tutores/buscar_tutor"
  get "tutores/buscar_persona" 
  get "tutores/tutor_detalle"
  get "tutores/agregar_tutor_detalle"
  post "tutores/guardar_tutor_detalle"
  get "tutores/eliminar_tutor_detalle"
  
  #CARGOS
  post 'cargos/lista'
  get 'cargos/lista'
  get 'cargos/agregar'
  post 'cargos/guardar'
  get 'cargos/eliminar'
  get 'cargos/editar'
  post 'cargos/actualizar'
  get 'cargos/index'

  #REMUNERACIONES EXTRAS
  post 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/agregar'
  post 'pagos_remuneraciones_extras/guardar'
  get 'pagos_remuneraciones_extras/eliminar'
  get 'pagos_remuneraciones_extras/editar'
  post 'pagos_remuneraciones_extras/actualizar'
  get 'pagos_remuneraciones_extras/index'

#DESCUENTOS
  post 'pagos_descuentos/lista'
  get 'pagos_descuentos/lista'
  get 'pagos_descuentos/agregar'
  post 'pagos_descuentos/guardar'
  get 'pagos_descuentos/eliminar'
  get 'pagos_descuentos/editar'
  post 'pagos_descuentos/actualizar'
  get 'pagos_descuentos/index'

#ADELANTOS
  post 'pagos_adelantos/lista'
  get 'pagos_adelantos/lista'
  get 'pagos_adelantos/agregar'
  post 'pagos_adelantos/guardar'
  get 'pagos_adelantos/eliminar'
  get 'pagos_adelantos/editar'
  post 'pagos_adelantos/actualizar'
  get 'pagos_adelantos/index'

#PAGOS DE SALARIOS
  get 'pagos_salarios/index'
  post 'pagos_salarios/lista'
  get 'pagos_salarios/lista'
  get 'pagos_salarios/agregar'
  post 'pagos_salarios/guardar'
  get 'pagos_salarios/eliminar'
  get 'pagos_salarios/salario_detalle'

  #ADELANTOS
  post 'registros_gastos/lista'
  get 'registros_gastos/lista'
  get 'registros_gastos/agregar'
  post 'registros_gastos/guardar'
  get 'registros_gastos/eliminar'
  get 'registros_gastos/editar'
  post 'registros_gastos/actualizar'
  get 'registros_gastos/index'
#---------------------------------------FONOWARE------------------------------------------------------------------------    
  #CRONTAB
  get "crontab_ultron/index"

  #JURISDICCIONES
  get "jurisdicciones/index"
  get "jurisdicciones/buscar_juridisccion_oferta" 

  #INFORMES
  get "informes/index"
  get "informes/index_gastos"
  get "informes/index_balance"
  get "informes/indexa"
  get "informes/generar_pdf"

  #DETALLES DEBITOS
  post "detalles_debitos/lista"
  get "detalles_debitos/lista"
  get "detalles_debitos/agregar"
  post "detalles_debitos/guardar"
  get "detalles_debitos/eliminar"
  get "detalles_debitos/editar"
  post "detalles_debitos/actualizar"
  get "detalles_debitos/index"
 
  #DETALLES CREDITOS
  post "detalles_creditos/lista"
  get "detalles_creditos/lista"
  get "detalles_creditos/agregar"
  post "detalles_creditos/guardar"
  get "detalles_creditos/eliminar"
  get "detalles_creditos/editar"
  post "detalles_creditos/actualizar"
  get "detalles_creditos/index"

  #PRODUCCION
  get "produccion/index"
  get "produccion/lista"
  post "produccion/lista"
  get "produccion/agregar"
  post "produccion/guardar"
  get "produccion/eliminar"
  get "produccion/editar"
  post "produccion/actualizar"
  get "produccion/produccion_detalle_credito"
  get "produccion/produccion_detalle_debito"
  get "produccion/agregar_detalle_credito"
  get "produccion/agregar_detalle_debito"
  post "produccion/guardar_detalle_credito"
  post "produccion/guardar_detalle_debito"
  get "produccion/eliminar_produccion_detalle_credito"
  get "produccion/eliminar_produccion_detalle_debito"
  get "produccion/cambiar_estado_solicitado_a_en_progreso"
  get "produccion/cambiar_estado_en_progreso_a_finalizado"
  get "produccion/cambiar_estado_cobro"
  get "produccion/cambiar_estado_cobro_desconfirmar"
  get "produccion/planilla_resumen_produccion"
  get "produccion/planilla_resumen_produccion_pdf"
  get "produccion/planilla_resumen_produccion_cliente"
  get "produccion/planilla_resumen_produccion_cliente_pdf"
  
  #PACIENTES
  post "pacientes/lista"
  get "pacientes/lista"
  get "pacientes/agregar"
  post "pacientes/guardar"
  get "pacientes/eliminar"
  get "pacientes/editar"
  post "pacientes/actualizar"
  get "pacientes/index"
  get "pacientes/buscar_paciente"
  get "pacientes/buscar_persona"
  get "pacientes/buscar_paciente_cita"

  #PACIENTES DETALLES FONO
  get "pacientes_detalles_fono/paciente_detalle_fono"
  post "pacientes_detalles_fono/guardar_detalle_fono"

  #HISTORIALES PACIENTES
  post "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/index"
  get "historiales_pacientes/historial_paciente_detalle_fono"
  get "historiales_pacientes/lista_citas"
  post "historiales_pacientes/lista_citas"
  get "historiales_pacientes/historial_cita_detalle_fono_terminado"
  


  #PROFESIONALES
  post "profesionales/lista"
  get "profesionales/lista"
  get "profesionales/agregar"
  post "profesionales/guardar"
  get "profesionales/eliminar"
  get "profesionales/editar"
  post "profesionales/actualizar"
  get "profesionales/index"
  get "profesionales/buscar_profesional"
  get "profesionales/buscar_persona"
  
  

  #PRECIOS
  post "precios/lista"
  get "precios/lista"
  get "precios/agregar"
  post "precios/guardar"
  get "precios/eliminar"
  get "precios/editar"
  post "precios/actualizar"
  get "precios/index"
  get "precios/obtener_datos"
  get "precios/buscar_precio"
  get "precios/marcar_predeterminado"

  #CITAS
  get "citas/index"
  post "citas/lista"
  get "citas/lista"
  get "citas/agregar"
  post "citas/guardar"
  get "citas/editar"
  post "citas/actualizar"
  get "citas/eliminar"
  get "citas/cambiar_estado_cita_en_espera_a_en_consultorio"
  get "citas/cambiar_estado_cita_en_consultorio_a_terminado"
  get "citas/cambiar_estado_cobro_a_cobrado"
  get "citas/cambiar_estado_cobro_a_no_cobrado"
  get "citas/cambiar_estado_cita_terminado_a_en_consultorio"
  get "citas/postergar_cita"
  post "citas/guardar_postergar_cita"
  get "citas/imprimir_informe"
  get "citas/generar_informe_pdf"
  get "citas/cambiar_estado_cita_en_consultorio_a_en_espera"
  

  #CITAS DETALLES FONO
  get "citas_detalles_fono/cita_detalle_fono"
  post "citas_detalles_fono/guardar_cita_detalle_fono"
  get "citas_detalles_fono/emitir_resolucion"
  post "citas_detalles_fono/guardar_resolucion"
  get "citas_detalles_fono/adjuntar_resolucion"
  post "citas_detalles_fono/guardar_resolucion_adjunta"
  get "citas_detalles_fono/habilitar_descarga_archivo"
  get "citas_detalles_fono/deshabilitar_descarga_archivo"
  get "citas_detalles_fono/cita_detalle_fono_terminado"

#--------------------------------------------SISTEMA------------------------------------------------------------  
  #PERSONAS
  post "personas/lista"
  get "personas/lista"
  get "personas/agregar"
  get "personas/agregar_persona_senatics"
  post "personas/guardar"
  post "personas/guardar_persona_senatics"
  get "personas/eliminar"
  get "personas/editar"
  post "personas/actualizar"
  get "personas/index"
  get "personas/mostrar_formulario"
  post "personas/unificar_persona"
  get "personas/obtener_datos"
  get "personas/buscar_persona_senatics"
  get "personas/buscar_chofer"
  

  #ROLES
  post "roles/lista"
  get "roles/lista"
  get "roles/agregar"
  post "roles/guardar"
  get "roles/eliminar"
  get "roles/editar"
  post "roles/actualizar"
  get "roles/accesos"
  get "roles/agregar_acceso"
  get "roles/guardar_acceso"
  get "roles/eliminar_acceso"
  get "roles/index"

  
  #CONTROLADORES
  post "controladores/lista"
  get "controladores/lista"
  get "controladores/agregar"
  post "controladores/guardar"

app/helpers/tutores_helper.rb
module TutoresHelper

	def link_to_editar_tutor(tutor_id)
		
	    render partial: 'link_to_editar_tutor', locals: { tutor_id: tutor_id }
	    
	end

	def link_to_tutor_detalle(tutor_id)
		
	    render partial: 'link_to_tutor_detalle', locals: { tutor_id: tutor_id }
	    
	end

	def tutor_avatar(tutor, options = {})
    if tutor.photo.nil?
      image_tag tutor.avatar_url, options
    else
      image_tag tutor.photo.thumb('150x150#').url, options
    end
  end
  
end

app/views/tutores/_agregar.html.erb
<%= javascript_include_tag "modulos/tutores.js" %>

<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
           
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar Tutor</h4>
      
    </div>

    <%= form_for @tutor, remote: true, url: tutores_guardar_url, html: { id: "form-agregar-tutor" }, method: 'POST' do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body"> 

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Tipo de Documento #{attr_requerido}".html_safe, id: "lbl-tipo-documento-persona" %></div>
          <div class="col-sm-7"><%= collection_select :persona, :tipo_documento_id,  TipoDocumento.habilitados.ordenado_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Nacionalidad #{attr_requerido}".html_safe, id: "lbl-nacionalidad" %></div>
          <div class="col-sm-7"><%= collection_select :persona, :nacionalidad_id, Nacionalidad.ordenado_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "N° Documento #{attr_requerido}".html_safe, id: "lbl-documento" %></div>
          <div class="col-sm-7"><%= text_field_tag :ci, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Nombre #{attr_requerido}".html_safe, id: "lbl-nombre" %></div>
          <div class="col-sm-7"><%= text_field_tag :nombres, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Apellido #{attr_requerido}".html_safe, id: "lbl-apellido" %></div>
          <div class="col-sm-7"><%= text_field_tag :apellidos, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Dirección #{attr_requerido}".html_safe, id: "lbl-direccion" %></div>
          <div class="col-sm-7"><%= text_field_tag :direccion, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Telefono".html_safe, id: "lbl-telefono" %></div>
          <div class="col-sm-7"><%= text_field_tag :telefono, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-md-4"><%= f.label nil, "Adjunto #{attr_requerido}".html_safe, id: "lbl-imagen" %></div>
          <div class="col-md-7">Imagen&hellip; <%= f.file_field :photo %></div>
          <div class="col-md-1"></div><br /><br />
          
       
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= link_to "Guardar","#" ,class: "btn btn-primary", id: "btn-guardar-tutor" %>
          
      </div>

    <% end %>

  </div>
  
</div>

<style type="text/css">

  #form-agregar-tutor label, #form-agregar-tutor input[type='text'], #form-agregar-tutor select , #form-agregar-tutor input[type='checkbox']{ float:left; margin-top:5px;}
  #form-agregar-tutor br {clear:both; }
  #form-agregar-tutor label { width:200px;font-size:12px;margin-top:10px;}
  #form-agregar-tutor #persona_tipo_documento_persona_id { width:60%;}
  #form-agregar-tutor #persona_nacionalidad_id { width:60%;}
  #form-agregar-tutor #persona_documento { width:50%;}


</style>

<script type="text/javascript">
  aplicar_datepicker2();
  
  setTimeout(function(){ 
    $("#persona_documento").focus();
    $("#persona_tipo_documento_id").val(1);
    $("#persona_nacionalidad_id").val(1);
  }, 1000);

  $("#ci").bind("keydown", function(e){
      
    if(e.keyCode == 13 || e.keyCode == 9){

    buscar_persona_v2($("#persona_tipo_documento_id").val(), $("#persona_nacionalidad_id").val(), $("#ci").val(),"<%= url_for(tutores_buscar_persona_path ) %>");
      return false;
    }
  })

  $("#btn-guardar-tutor").bind('click', function () {

      valido = true
      msg = ""

      if($("#persona_tipo_documento_id").val().length == 0){

        msg +="Debe seleccionar el tipo de documento.\n"
        valido = false
      
      }

       if($("#persona_nacionalidad_id").val().length == 0){

        msg +="Debe seleccionar una nacionalidad.\n"
        valido = false
      
      }

      if($("#ci").val().length == 0){

        msg +="El documento del tutor no puede estar vacío.\n"
        valido = false
      
      }

      if($("#nombres").val().length == 0){

        msg +="Es necesario ingresar el nombre.\n"
        valido = false
      
      }

      if($("#apellidos").val().length == 0){

        msg +="Es necesario ingresar el apellido.\n"
        valido = false
      
      }


      if($("#direccion").val().length == 0){

        msg +="Debe ingrear una dirección.\n"
        valido = false
      
      }

      if (valido){

        swal({
          title: "Confirmar tutor",
          text: "Al confirmar el tutor estará diponible para asignar a alumnos",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

            $("#form-agregar-tutor").submit();
            
          } 

        });

      }else{

        swal(msg);
      
      }

      return false;
    
    })

</script>

app/views/tutores/_agregar_tutor_detalle.html.erb
<%= javascript_include_tag "modulos/alumnos.js" %>
<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar Alumno al Tutor</h4>
      
    </div>

    <%= form_for @tutor_detalle, remote: true, url: tutores_guardar_tutor_detalle_url, html: { id: "form-agregar-tutor-detalle" } do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>

      <%= hidden_field_tag :tutor_id, params[:tutor_id]%>



      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "N° Documento #{attr_requerido}".html_safe, id: "lbl-documento" %></div>
          <div class="col-sm-7"><%= text_field_tag :ci, nil, class: 'form-control input-sm' %></div>
          <em class="msg"></em>
          <div class="col-sm-1"></div><br />

          <%= hidden_field_tag :alumno_id%>

          <div class="col-sm-4"><%= label_tag nil, "Nombre #{attr_requerido}".html_safe, id: "lbl-nombre" %></div>
          <div class="col-sm-7"><%= text_field_tag :nombres, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Apellido #{attr_requerido}".html_safe, id: "lbl-apellido" %></div>
          <div class="col-sm-7"><%= text_field_tag :apellidos, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Parentezco #{attr_requerido}".html_safe, id: "lbl-parentezco" %></div>
          <div class="col-sm-7"><%= collection_select :parentezco, :id, Parentezco.orden_01, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br /><br />

      </div>
      
    </div>        
       
      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= link_to "Guardar","#", class: "btn btn-primary", id: "btn-guardar-tutor-detalle" %> 
          
      </div>
    
    <% end %>

  </div>
</div>

<style type="text/css">

  #form-agregar-tutor-detalle label, #form-agregar-tutor-detalle input[type='text'] { float:left; margin-top:5px;}
  #form-agregar-tutor-detalle br {clear:both; }
  #form-agregar-tutor-detalle label { width:200px; font-size:12px;}

</style>

<script type="text/javascript">

  

  aplicar_datepicker2();

   function isNumberKey(evt)
  {
     var charCode = (evt.which) ? evt.which : event.keyCode
     if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode != 46) {
         
         return false;
     }

     return true;
  }

  $("#btn-guardar-tutor-detalle").bind('click', function () {

      valido = true
      msg = ""

      if($("#alumno_id").val().length == 0){

        msg +="Debe agregar un alumno. \n"
        valido = false
      
      }

       if($("#ci").val().length == 0){

        msg +="El número de documento no puede estar vacío \n"
        valido = false
      
      }

       if($("#parentezco_id").val().length == 0){

        msg +="Debe seleccionar el tipo de parentezco. \n"
        valido = false
      
      }


      if (valido){

        swal({
          title: "Confirmar Alumno",
          text: "Al confirmar el alumno estará bajo la tutela de la persona asignada.",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

            $("#form-agregar-tutor-detalle").submit();
            
          } 

        });

      }else{

        swal(msg);
      
      }

      return false;
    
    })

  //agregar alumno por numero de CI
    $("#ci").bind("keydown", function(e){
      
    if(e.keyCode == 13 || e.keyCode == 9){

    buscar_alumno( $("#ci").val(),"<%= url_for(alumnos_buscar_alumno_documento_path ) %>");

      return false;
    }
  })

</script>

app/views/tutores/_link_to_editar_tutor.html.erb
<%= link_to icon_editar, "#", id: "link-to-editar-tutor-#{tutor_id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar datos del tutor.', onclick: "$('.modal').html('');return false;" %>
<%= modal_window( window_id: "modal-window-editar-tutor", link_to_id: "#link-to-editar-tutor-#{tutor_id}", url: tutores_editar_path( window_id: "modal-window-editar-tutor", tutor_id: tutor_id) )%>

app/views/tutores/_link_to_tutor_detalle.html.erb
<%= link_to icon_detalles, "#", id: "link-to-tutor-detalle-#{tutor_id}", class: 'btn btn-success btn-torneo-detalle btn-xs', title: 'Haga click aquí para ver los pilotos inscriptos.', onclick: "$('.modal').html('');return false;" %>

<script type="text/javascript">

  $("#link-to-tutor-detalle-<%= tutor_id %>").bind('click', function(){

    var contenido = $.trim($("#tutor-detalle-<%= tutor_id %>").html());

    $(".tutor-detalle").html('');

    if(contenido.length == 0){

    $(this).parent().parent().after("<tr id='tutor-detalle-<%= tutor_id %>' class='tutor-detalle'><td colspan='12' style='text-align:center;'><i class='fa fa-refresh fa-spin'></i> Cargando...</td></tr>")

      $.ajax({

        type: 'GET',
        url: '<%= url_for(tutores_tutor_detalle_path) %>',  
        data: { tutor_id: <%= tutor_id %>},
        dataType: 'script'
        
      })
 
    }
    
    return false;
  })

</script>

app/views/tutores/_tutor_detalle.html.erb
<td colspan="12">

  <div style="background: #e6e6e6; margin:15px;padding:15px;border-radius:10px;">

    <div>

      <div class="col-sm-12" style="border-bottom: 2px dashed #b6b6b6;margin-bottom:5px;padding:0px;">
        <h3 style="float:left;margin-top:5px;">Tutores Detalles</h3>
        <%= link_to "<i class='glyphicon glyphicon-plus-sign'></i> agregar alumno".html_safe, "#", id: "link-to-agregar-tutor-detalle", class: "btn btn-primary btn-xs", style: "float:right;" %>
      </div>

    </div> 

    <div style="clear:both;"></div>
   
    <div class="panel-body">
      
      <div class="table-responsive" id="table-tutor-detalle">
          
        <table class="table table-bordered table-hover table-striped display dataTable" aria-describedby="example_info">
            
          <thead>
              
            <tr role="row">
              
              <th>ID</th>
              <th>Nombre Alumno</th>
              <th>CI Alumno</th>
              <th>Tipo Parentezco</th>
              <th style='text-align:right;'></th>
              
            </tr>
            
          </thead>
       
          <tbody id="tutor-detalle-lista">

            <% if @tutor_detalle.present? %>
            
              <% @tutor_detalle.each do |id|%>

                <tr>
                  <td><%= id.tutor_detalle_id%></td>
                  <td><%= id.nombre_alumno %></td>
                  <td><%= id.alumno_ci %></td>
                  <td><%= id.parentezco %></td>
                  <td style="width: 50px;text-align:right;">
                    <%= link_to icon_eliminar,"#", onclick: "eliminar_registro(#{id.tutor_detalle_id});return false;", class: "btn btn-danger btn-xs", id: "btn-eliminar-tutor-detalle", title: 'Haga click para eliminar al Alumno de la tutela.'  %>
                  </td>

                </tr>

              <% end %>

              <tr id="tab-paginacion">

                <td colspan="12" style="text-align:center;"><div class="flickr_pagination"><%= ajax_will_paginate @tutor_detalle, :params => params %></div></td>
              </tr>

            <% else %>

              <tr><td colspan=3>No se han encontrado datos.</td></tr>

            <% end %>
                
          </tbody>
              
        </table>
        
      </div>
      
    </div>
    
  </div>

  <%= modal_window( window_id: "modal-window-agregar-tutor-detalle", link_to_id: "#link-to-agregar-tutor-detalle", url: tutores_agregar_tutor_detalle_path( window_id: "modal-window-agregar-tutor-detalle", tutor_id: params[:tutor_id]) )%>

</td>


  <script type="text/javascript">

    function eliminar_registro(tutor_detalle_id) {

        swal({
          title: "Confirmar",
          text: "Al confirmar el alumno dejará de estar bajo la tutela de la persona.",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

              $.ajax({
                url: "<%= url_for(tutores_eliminar_tutor_detalle_path) %>", 
                data: {tutor_detalle_id: tutor_detalle_id},
                dataType: 'script'
              });
            
          } else{

            return false;

          }

        });

    
    }

    

  </script>

app/views/tutores/agregar_tutor_detalle.js.erb
$("#<%= params[:window_id]%>").html('');
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'agregar_tutor_detalle')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/tutores/lista.js.erb
$("#tutores-lista").html("<%= escape_javascript(render partial: "lista", locals: { tutor: @tutores }) %>");

app/views/tutores/tutor_detalle.js.erb
$("#tutor-detalle-<%= params[:tutor_id]%>").html("<%= escape_javascript(render :partial => 'tutor_detalle')%>");