config/routes.rb
  get "tutores/buscar_persona" 
  get "tutores/tutor_detalle"
  get "tutores/agregar_tutor_detalle"
  post "tutores/guardar_tutor_detalle"
  get "tutores/eliminar_tutor_detalle"
  
  #CARGOS
  post 'cargos/lista'
  get 'cargos/lista'
  get 'cargos/agregar'
  post 'cargos/guardar'
  get 'cargos/eliminar'
  get 'cargos/editar'
  post 'cargos/actualizar'
  get 'cargos/index'

  #REMUNERACIONES EXTRAS
  post 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/agregar'
  post 'pagos_remuneraciones_extras/guardar'
  get 'pagos_remuneraciones_extras/eliminar'
  get 'pagos_remuneraciones_extras/editar'
  post 'pagos_remuneraciones_extras/actualizar'
  get 'pagos_remuneraciones_extras/index'

#DESCUENTOS
  post 'pagos_descuentos/lista'
  get 'pagos_descuentos/lista'
  get 'pagos_descuentos/agregar'
  post 'pagos_descuentos/guardar'
  get 'pagos_descuentos/eliminar'
  get 'pagos_descuentos/editar'
  post 'pagos_descuentos/actualizar'
  get 'pagos_descuentos/index'

#ADELANTOS
  post 'pagos_adelantos/lista'
  get 'pagos_adelantos/lista'
  get 'pagos_adelantos/agregar'
  post 'pagos_adelantos/guardar'
  get 'pagos_adelantos/eliminar'
  get 'pagos_adelantos/editar'
  post 'pagos_adelantos/actualizar'
  get 'pagos_adelantos/index'

#PAGOS DE SALARIOS
  get 'pagos_salarios/index'
  post 'pagos_salarios/lista'
  get 'pagos_salarios/lista'
  get 'pagos_salarios/agregar'
  post 'pagos_salarios/guardar'
  get 'pagos_salarios/eliminar'
  get 'pagos_salarios/salario_detalle'

  #ADELANTOS
  post 'registros_gastos/lista'
  get 'registros_gastos/lista'
  get 'registros_gastos/agregar'
  post 'registros_gastos/guardar'
  get 'registros_gastos/eliminar'
  get 'registros_gastos/editar'
  post 'registros_gastos/actualizar'
  get 'registros_gastos/index'
#---------------------------------------FONOWARE------------------------------------------------------------------------    
  #CRONTAB
  get "crontab_ultron/index"

  #JURISDICCIONES
  get "jurisdicciones/index"
  get "jurisdicciones/buscar_juridisccion_oferta" 

  #INFORMES
  get "informes/index"
  get "informes/index_gastos"
  get "informes/index_balance"
  get "informes/indexa"
  get "informes/generar_pdf"

  #DETALLES DEBITOS
  post "detalles_debitos/lista"
  get "detalles_debitos/lista"
  get "detalles_debitos/agregar"
  post "detalles_debitos/guardar"
  get "detalles_debitos/eliminar"
  get "detalles_debitos/editar"
  post "detalles_debitos/actualizar"
  get "detalles_debitos/index"
 
  #DETALLES CREDITOS
  post "detalles_creditos/lista"
  get "detalles_creditos/lista"
  get "detalles_creditos/agregar"
  post "detalles_creditos/guardar"
  get "detalles_creditos/eliminar"
  get "detalles_creditos/editar"
  post "detalles_creditos/actualizar"
  get "detalles_creditos/index"

  #PRODUCCION
  get "produccion/index"
  get "produccion/lista"
  post "produccion/lista"
  get "produccion/agregar"
  post "produccion/guardar"
  get "produccion/eliminar"
  get "produccion/editar"
  post "produccion/actualizar"
  get "produccion/produccion_detalle_credito"
  get "produccion/produccion_detalle_debito"
  get "produccion/agregar_detalle_credito"
  get "produccion/agregar_detalle_debito"
  post "produccion/guardar_detalle_credito"
  post "produccion/guardar_detalle_debito"
  get "produccion/eliminar_produccion_detalle_credito"
  get "produccion/eliminar_produccion_detalle_debito"
  get "produccion/cambiar_estado_solicitado_a_en_progreso"
  get "produccion/cambiar_estado_en_progreso_a_finalizado"
  get "produccion/cambiar_estado_cobro"
  get "produccion/cambiar_estado_cobro_desconfirmar"
  get "produccion/planilla_resumen_produccion"
  get "produccion/planilla_resumen_produccion_pdf"
  get "produccion/planilla_resumen_produccion_cliente"
  get "produccion/planilla_resumen_produccion_cliente_pdf"
  
  #PACIENTES
  post "pacientes/lista"
  get "pacientes/lista"
  get "pacientes/agregar"
  post "pacientes/guardar"
  get "pacientes/eliminar"
  get "pacientes/editar"
  post "pacientes/actualizar"
  get "pacientes/index"
  get "pacientes/buscar_paciente"
  get "pacientes/buscar_persona"
  get "pacientes/buscar_paciente_cita"

  #PACIENTES DETALLES FONO
  get "pacientes_detalles_fono/paciente_detalle_fono"
  post "pacientes_detalles_fono/guardar_detalle_fono"

  #HISTORIALES PACIENTES
  post "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/index"
  get "historiales_pacientes/historial_paciente_detalle_fono"
  get "historiales_pacientes/lista_citas"
  post "historiales_pacientes/lista_citas"
  get "historiales_pacientes/historial_cita_detalle_fono_terminado"
  


  #PROFESIONALES
  post "profesionales/lista"
  get "profesionales/lista"
  get "profesionales/agregar"
  post "profesionales/guardar"
  get "profesionales/eliminar"
  get "profesionales/editar"
  post "profesionales/actualizar"
  get "profesionales/index"
  get "profesionales/buscar_profesional"
  get "profesionales/buscar_persona"
  
  

  #PRECIOS
  post "precios/lista"
  get "precios/lista"
  get "precios/agregar"
  post "precios/guardar"
  get "precios/eliminar"
  get "precios/editar"
  post "precios/actualizar"
  get "precios/index"
  get "precios/obtener_datos"
  get "precios/buscar_precio"
  get "precios/marcar_predeterminado"

  #CITAS
  get "citas/index"
  post "citas/lista"
  get "citas/lista"
  get "citas/agregar"
  post "citas/guardar"
  get "citas/editar"
  post "citas/actualizar"
  get "citas/eliminar"
  get "citas/cambiar_estado_cita_en_espera_a_en_consultorio"
  get "citas/cambiar_estado_cita_en_consultorio_a_terminado"
  get "citas/cambiar_estado_cobro_a_cobrado"
  get "citas/cambiar_estado_cobro_a_no_cobrado"
  get "citas/cambiar_estado_cita_terminado_a_en_consultorio"
  get "citas/postergar_cita"
  post "citas/guardar_postergar_cita"
  get "citas/imprimir_informe"
  get "citas/generar_informe_pdf"
  get "citas/cambiar_estado_cita_en_consultorio_a_en_espera"
  

  #CITAS DETALLES FONO
  get "citas_detalles_fono/cita_detalle_fono"
  post "citas_detalles_fono/guardar_cita_detalle_fono"
  get "citas_detalles_fono/emitir_resolucion"
  post "citas_detalles_fono/guardar_resolucion"
  get "citas_detalles_fono/adjuntar_resolucion"
  post "citas_detalles_fono/guardar_resolucion_adjunta"
  get "citas_detalles_fono/habilitar_descarga_archivo"
  get "citas_detalles_fono/deshabilitar_descarga_archivo"
  get "citas_detalles_fono/cita_detalle_fono_terminado"

#--------------------------------------------SISTEMA------------------------------------------------------------  
  #PERSONAS
  post "personas/lista"
  get "personas/lista"
  get "personas/agregar"
  get "personas/agregar_persona_senatics"
  post "personas/guardar"
  post "personas/guardar_persona_senatics"
  get "personas/eliminar"
  get "personas/editar"
  post "personas/actualizar"
  get "personas/index"
  get "personas/mostrar_formulario"
  post "personas/unificar_persona"
  get "personas/obtener_datos"
  get "personas/buscar_persona_senatics"
  get "personas/buscar_chofer"
  

  #ROLES
  post "roles/lista"
  get "roles/lista"
  get "roles/agregar"
  post "roles/guardar"
  get "roles/eliminar"
  get "roles/editar"
  post "roles/actualizar"
  get "roles/accesos"
  get "roles/agregar_acceso"
  get "roles/guardar_acceso"
  get "roles/eliminar_acceso"
  get "roles/index"

  
  #CONTROLADORES
  post "controladores/lista"
  get "controladores/lista"
  get "controladores/agregar"
  post "controladores/guardar"
  get "controladores/eliminar"
  get "controladores/editar"
  post "controladores/actualizar"
  get "controladores/acciones"
  get "controladores/agregar_accion"
  post "controladores/guardar_accion"
  get "controladores/eliminar_accion"
  get "controladores/index"

  
  #USUARIOS
  get "usuarios/cambiar_perfil_actual"
  get "usuarios/mi_cuenta"
  post "usuarios/actualizar_mi_cuenta"
  post "usuarios/actualizar_mi_password"
  get "usuarios/perfiles"
  get "usuarios/agregar_perfil"
  get "usuarios/guardar_perfil"
  get "usuarios/eliminar_perfil"
  post "usuarios/actualizar_password"
  get "usuarios/reset_password"
  get "usuarios/perfiles"
  get 'usuarios/index'
  get 'usuarios/lista'
  post 'usuarios/lista'
  get "usuarios/agregar"
  post "usuarios/guardar"
  get "usuarios/eliminar"
  get "usuarios/editar"
  post "usuarios/actualizar"
  get 'usuarios/buscar_persona'
  post 'usuarios/cambiar_estado_usuario'

  #LOGIN
  get 'login' => "usuarios_sessions#new",      :as => :login
  get 'logout' => "usuarios_sessions#destroy", :as => :logout
  post "usuarios_sessions/create"
  get "usuarios_sessions/acceso_denegado"
  get "usuarios_sessions/new"  
  get "usuarios_sessions/mantenimiento"  

  get "principal/buscar_institucion"
  get "principal/buscar_persona"
  get "principal/buscar_usuario"
  post "principal/guardar_recuperar_password"
  get "principal/recuperar_password"
  post "principal/guardar_usuario"
  get "principal/activar_cuenta"
  get "principal/agregar_usuario"
  get "contactos" => "principal#contactos", :as => :contactos
  get "index" => "principal#index", :as => :index
  get "about" => "principal#about", :as => :about
  get "legal" => "principal#legal", :as => :legal
  get "index" => "principal#index", :as => :indexv
	
	

  root 'principal#index'
  
  get "application/autocompletar" => 'application#autocompletar', :as => :autocompletar

  #INFORMACIONES
  get "informaciones/index"
  get "informaciones/lista"
  post "informaciones/lista"
	get "informaciones/perfiles"
	get "informaciones/enlaces"
  get "informaciones/agregar"
  post "informaciones/guardar"
	get "informaciones/agregar_enlace"
	get "informaciones/guardar_enlace"
	post "informaciones/guardar_enlace"
	get "informaciones/agregar_perfil"
  get "informaciones/guardar_perfil"
  get "informaciones/eliminar"
  get "informaciones/editar"
  post "informaciones/actualizar"
	get "informaciones/editar_enlace"
	post "informaciones/actualizar_enlace"
  get "informaciones/eliminar_enlace"

app/models/precio.rb
class Precio < ActiveRecord::Base
  
  self.table_name= "precios"
  self.primary_key = "id"
  
  attr_accessible :id, :codigo, :descripcion, :monto, :periodo_escolar_id, :created_at, :updated_at
 
  scope :orden_01, -> { order("id")}

  
end

app/controllers/precios_controller.rb
class PreciosController < ApplicationController

before_filter :require_usuario

  def index
  end

  def lista

    cond = []
    args = []

    if params[:form_buscar_precios_id].present?

      cond << "id = ?"
      args << params[:form_buscar_precios_id]

    end

    if params[:form_buscar_precios_descripcion].present?

      cond << "descripcion ilike ?"
      args << "%#{params[:form_buscar_precios_descripcion]}%"

    end

    if params[:form_buscar_precios_monto].present?

      cond << "monto = ?"
      args << params[:form_buscar_precios_monto]

    end

    cond = cond.join(" and ").lines.to_a + args if cond.size > 0

    if cond.size > 0

      @precios =  VPrecio.orden_01.where(cond).paginate(per_page: 10, page: params[:page])
      @total_encontrados = Precio.where(cond).count

    else

      @precios = VPrecio.orden_01.paginate(per_page: 10, page: params[:page])
      @total_encontrados = Precio.count

    end

    @total_registros = Precio.count

    respond_to do |f|

      f.js

    end

  end

  def agregar

    @precio = Precio.new

    respond_to do |f|

      f.js
      
    end

  end

  def guardar

    valido = true
    @msg = ""
    @precio_ok = false
    @precio = Precio.where('descripcion = ? and turno_id =? and periodo_escolar_id = ?',params[:precio][:descripcion].upcase, params[:precio][:turno_id], params[:precio][:periodo_escolar_id]).first

    if @precio.present?
      @msg = "Precio ya existe."
      valido = false
    end

    if valido
    
      @precio = Precio.new()
      @precio.descripcion = params[:precio][:descripcion].upcase
      @precio.monto = params[:precio][:monto].to_s.gsub(/[$.]/,'').to_i
      @precio.turno_id = params[:precio][:turno_id]
      @precio.periodo_escolar_id = params[:precio][:periodo_escolar_id]

      if @precio.save

        auditoria_nueva("registrar precio", "precios", @precio)
       
        @precio_ok = true
       

      end

    end 
  
      rescue Exception => exc  
        # dispone el mensaje de error 
        #puts "Aqui si muestra el error ".concat(exc.message)
        if exc.present?        
        @excep = exc.message.split(':')    
        @msg = @excep.to_s
      
      end                
               
    respond_to do |f|

      f.js

    end

  end

  def eliminar

    valido = true
    @msg = ""

    @precio = Precio.find(params[:id])

    @precio_elim = @precio

    if valido

      if @precio.destroy

        auditoria_nueva("eliminar precio", "precios", @precio)

        @eliminado = true

      else

        @msg = "ERROR: No se ha podido eliminar el precio."

      end

    end
        rescue Exception => exc  
        # dispone el mensaje de error 
        #puts "Aqui si muestra el error ".concat(exc.message)
        if exc.present?        
        @excep = exc.message.split(':')    
        @msg = @excep[3].concat(" "+@excep[4])
        @eliminado = false
        end
        
    respond_to do |f|

      f.js

    end

  end

  def editar

    @precio = Precio.find(params[:id])

    respond_to do |f|

      f.js

    end

  end

  def actualizar

    valido = true
    @msg = ""

    @precio = Precio.find(params[:precio][:id])
    auditoria_id = auditoria_antes("actualizar precio", "precios", @precio)

    if valido

      @precio.descripcion = params[:precio][:descripcion].upcase
      @precio.monto =  params[:precio][:monto].to_s.gsub(/[$.]/,'').to_i
      @precio.turno_id = params[:precio][:turno_id]
      @precio.periodo_escolar_id = params[:precio][:periodo_escolar_id]

      if @precio.save

        auditoria_despues(@precio, auditoria_id)
        @precio_ok = true

      end

    end
      rescue Exception => exc  
      # dispone el mensaje de error 
      #puts "Aqui si muestra el error ".concat(exc.message)
      if exc.present?        
        @excep = exc.message.split(':')    
        @msg = @excep[3].concat(" "+@excep[4])
      end                
        
    respond_to do |f|

      f.js

    end

  end
  

  def buscar_precio

     @precios = Precio.where("descripcion ilike ?", "%#{params[:descripcion]}%")

    respond_to do |f|
      
      f.html
      f.json { render :json => @precios }
    
    end

  end

  def marcar_predeterminado

    @guardado_ok = false    
    @msg = ""

    Precio.update_all(predeterminado: false)

    @precio = Precio.where("id = ?", params[:id]).first
    auditoria_id = auditoria_antes("Marcar precio predeterminado", "precios", @precio)
    @precio.predeterminado = true

    if @precio.save

        auditoria_despues(@precio, auditoria_id)
        @guardado_ok = true
        @msg = "Precio marcado como predeterminado exitosamente."

    end
    
    rescue Exception => exc  
      # dispone el mensaje de error 
      #puts "Aqui si muestra el error ".concat(exc.message)
      if exc.present?        
        @excep = exc.message.split(':')    
        @msg = @excep[3].concat(" "+@excep[4])
        @eliminado = false
      end
        
    respond_to do |f|

      f.js

    end

  end



end

app/helpers/precios_helper.rb
module PreciosHelper

  def link_to_editar_precio(precio)

      render partial: 'link_to_editar_precio', locals: { precio: precio }
      
  end

  def verificar_predeterminado(precio_id)

    @precio = Precio.where("id = ?", precio_id).first
    
    
      return @precio.predeterminado

   
  end
  
end

app/views/precios/_link_to_editar_precio.html.erb
<%= link_to icon_editar, "#", id: "link-to-editar-precio-#{precio.id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar el precio.', onclick: "$('.modal').html('');return false;" %>


<%= modal_window( window_id: "modal-window-editar-precio", link_to_id: "#link-to-editar-precio-#{precio.id}", url: precios_editar_path( window_id: "modal-window-editar-precio", id: precio.id) )%>

app/views/precios/_lista.html.erb
<% if precios.present? %>

  <% precios.each do |pre| %>

    <tr>

      <td><%= pre.id %></td>
      <td><%= pre.descripcion%></td>
      <td><%= pre.monto.to_s.reverse.gsub(/...(?=.)/,'\&.').reverse %></td>
      <td><%= pre.turno%></td>
      <%#= check_box_tag "predeterminado", nil, verificar_predeterminado(pre.id) %>

      <td style="width:120px;"> 

        <%= link_to_editar_precio(pre) %>
        
        <%= link_to icon_eliminar,"#", onclick: "eliminar_registro(#{pre.id});return false;", class: "btn btn-danger btn-xs", id: "btn-eliminar-precio", title: 'Haga click para eliminar el precio'  %>
         
       </td>

     
     

      </td>

    </tr>

  <% end %>

<tr id="tab-paginacion">

    <td colspan="12" style="text-align:center;"><div class="flickr_pagination"><%= ajax_will_paginate precios, :params => params %></div></td>
</tr>

<tr>
    <td colspan="12">
      Cantidad de registros encontrados: <%= @total_encontrados %> 
    </td>
</tr>

 

<% else %>

  <tr>

    <td colspan="12"><p class='none-result'>No se han encontrado resultados.</p></td>

  </tr>


<% end %>


<script type="text/javascript">

  function eliminar_registro(precio_id) {

        swal({
          title: "Confirmar",
          text: "Al confirmar se eliminará permanentemente de la lista de precios",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

              $.ajax({
                url: "<%= url_for(precios_eliminar_path) %>", 
                data: {id: precio_id},
                dataType: 'script'
              });
            
          } else{

            return false;

          }

        });

    
    }

    function marcar_predeterminado(precio_id) {

        swal({
          title: "Confirmar",
          text: "Al confirmar este precio como predeterminado éste quedara como principal al crear una cita.",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

              $.ajax({
                url: "<%= url_for(precios_marcar_predeterminado_path) %>", 
                data: {id: precio_id},
                dataType: 'script'
              });
            
          } else{

            return false;

          }

        });

    
    }

</script>

app/views/precios/actualizar.js.erb
<% if @precio_ok.present? %>

   $("<div class='col-sm-12' id='msg-editar-precio' style='color:#000;padding-top:5px;font-size:10px;background:#d6ffd6;border-radius:5px;text-align:center;'>Actualizado Exitosamente.</div>").insertBefore("#form-editar-precio");
   
  $("#form_buscar_precios_id").val('<%= @precio.id %>');
  $("#form_buscar_precios_codigo").val('');
  $("#form_buscar_precios_monto").val('');
  $("#form_buscar_precios_descripcion").val('');
  $("#form_buscar_precios_nivel_id").val('');

  setTimeout(function(){ 

    $("#<%= params[:window_id]%>").modal('hide'); 
    $("#form-buscar-precios").submit();
    swal("Guardado Exitosamente.");

  }, 3000);

<% else %>

  $("<div class='col-sm-12' id='msg-editar-precio' style='color:#000;padding-top:5px;font-size:10px;background: #f8dfdf;border-radius:5px;text-align:center;'><%= j(@msg) %></div>").insertBefore("#form-editar-precio");

<% end %>

app/views/precios/eliminar.js.erb
<% if @eliminado %>

   $("<div class='col-sm-12' id='msg-eliminar-precio' style='color:#000;padding-top:5px;font-size:10px;background:#d6ffd6;border-radius:5px;text-align:center;'>Eliminado exitosamente.</div>").insertBefore("#table-precios");
   $("#form_buscar_precios_id").val("<%=@precio_elim.id%>")
   $("#form-buscar-precios").submit();
    setTimeout(function(){ 
      
      $("#msg-eliminar-precio").remove();
      swal("Eliminado Exitosamente.");

    }, 1000);
      
<% else %>

  $("<div class='col-sm-12' id='msg-eliminar-precio' style='color:#000;padding-top:5px;font-size:10px;background: #f8dfdf;border-radius:5px;text-align:center;'><%= j(@msg).html_safe %></div>").insertBefore("#table-precios");
  setTimeout(function(){ $("#msg-eliminar-precio").remove(); }, 2000);
  	swal("no se pudo Eliminar.")
    
<% end %>

app/views/precios/index.html.erb
<%= javascript_include_tag "sweetalert.min" %>
<%= stylesheet_link_tag "sweetalert" %>
<div>

  <div class="col-sm-12" style="border-bottom: 2px solid #b6b6b6;margin-bottom:5px;padding:0px;">
    <h3 style="float:left;margin-top:5px;">Precios</h3>
    <%= link_to "<i class='glyphicon glyphicon-plus-sign'></i> agregar".html_safe, "#", id: "link-to-agregar-precio", class: "btn btn-primary pull-right", style: "float:right;margin-left:10px;", onclick: "$('.modal').html('');return false;" %>
    <%= modal_window( window_id: "modal-window-agregar-precio", link_to_id: "#link-to-agregar-precio", url: precios_agregar_path( window_id: "modal-window-agregar-precio") )%>
    
  </div>
</div>

<div style="clear:both;"></div>
 
<div class="table-responsive" id="table-precios">

  <table class="table table-small-font table-bordered table-striped" style="font-size:11px;">
   
    <thead>

      <%= form_tag precios_lista_path, remote: true, id: "form-buscar-precios"  do  %>

        <tr>

          <th style="width:10%;">
            <span>ID</span>
            <div class="input-group input-group-sm">
              <%= text_field_tag :form_buscar_precios_id, nil, :class => 'form-control', :placeholder => "" %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-precios', '#form_buscar_precios_id');"><i class="fa fa-times"></i></span>
            </div>
          </th>

          <th style="width:25%;">
            <span>Descripción</span>
            <div class="input-group input-group-sm">
                <%= text_field_tag :form_buscar_precios_descripcion, nil, :class => 'form-control', :placeholder => "" %>
                <span class="input-group-addon limpiar" onclick="$('#form_buscar_precios_id').val('');quitar_filtro('#form-buscar-precios', '#form_buscar_precios_descripcion');"><i class="fa fa-times"></i></span>
            </div>

            <%= hidden_field_tag :form_buscar_precios_descripcion %>
            <%= autocomplete_help( ruta:  autocompletar_path(atributo_id: :id,
                  atributo_descripcion: :descripcion,
                  atributo_tipo: :text, 
                  model: :Precio, 
                  limit: 10,
                  cadena_consulta: "upper(quitar_acentos(descripcion))",
                  orden: "descripcion"), 
              parametro_id: "form_buscar_precios_descripcion", 
              resultado_id: "form_buscar_precios_id",
              min_length: 2
              ) %>
          </th>


          <th style="width:10%;">
            <span>Monto</span>
            <div class="input-group input-group-sm">
              <%= text_field_tag :form_buscar_precios_monto, nil, :class => 'form-control', :placeholder => "" %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-precios', '#form_buscar_precios_monto');"><i class="fa fa-times"></i></span>
            </div>
          </th>

          <th style="width:10%;">
           <span >Turno</span>
            <div class="input-group input-group-sm">
              <%= collection_select :form_buscar_precios, :turno_id, Turno.orden_descripcion, :id, :descripcion, { include_blank: true}, {:class => 'form-control input-sm', style: "font-size:9px;"} %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-precios', '#form_buscar_precios_turno_id');"><i class="fa fa-times"></i></span>
            </div>
          </th>



          <th style="width:15%;"></th>

        </tr>

        <% end %>

      </thead> 

    <tbody id="precios-lista"></tbody>
  
  </table>

</div>




<script type="text/javascript">

  //---------------------------- RECUPERANDO DATOS ----------------------------//
  $("#form-buscar-precios").bind("submit", function () {
    var valido = true;
    if($("#form_buscar_precios_descripcion").val().length !== 0 ){
      valido = false;
      if(($("#form_buscar_precios_descripcion").val().replace(/\s/g,'')).length > 2 && ($("#form_buscar_precios_descripcion").val().replace(/\s/g,'')).length > 2){        
        valido = true;
      }else{
        valido = false;
        //swal("Para la búsqueda por Nombre y Apellido Ingrese minimo 3(tres) carácteres en cada caja de texto", "", "error");         
        $(".nmb").html('*Ingrese minimo 3(tres) carácteres para cada caja de texto');
        $(".nmb").attr({'style':'color: red;font-size: 8px;'});      
      }      
    }
      
    if(valido){
    $(".nmb").html('');       
    $("#precios-lista").html("<%= escape_javascript("<tr><td colspan='9' style='text-align:center;'>#{image_tag('ajax-loader0.gif')}</td></tr>").html_safe %>")      
    }

    

  })
 
  //---------------------------------------------------------------------------//
  //---------------------------- BUSCAR PERSONAS-------- -------------------------//
  $("#table-precios input, #table-precios select").bind('change', function () {
      $.ajaxQ.abortAll();
      $("#form-buscar-precios").submit();

  })
  //----------------------------------------------------------------------------//
  //----------------------------INICIO -----------------------------------------//
  aplicar_datepicker();
  $("#form-buscar-precios").submit();
  <% if params[:agregar] %>
    $("#link-to-agregar-precio").trigger('click');
  <% end %>
  //----------------------------------------------------------------------------//
</script>

<style>
    /*INTRO.JS*/
    .introjs-helperNumberLayer{
        width: 23px;
        height: 23px;
        padding: 0px;
    }

    #start-tour{
        cursor: pointer;
    }

    #form-buscar-precios table th { background:#e6e6e6;}
    #form-buscar-precios table th span.limpiar { background:#fff;}

</style>

app/views/precios/lista.js.erb
$("#precios-lista").html("<%= escape_javascript(render partial: "lista", locals: { precios: @precios }) %>");